from django.db import models

class Orden(models.Model):
    id_order = models.IntegerField(default=0,null=False,unique=True)
    name = models.CharField(verbose_name='Cliente',max_length=250,null=True)
    Descuentopociento = models.IntegerField(default=0)
    cobrarimpuesto = models.BooleanField(default=False)
    propina = models.BooleanField(default=False)
    SaldoCliente = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    CobrarValorExtra = models.BooleanField(default=False)
    NombreClientePrepago = models.CharField(max_length=250,null=True)
    CantPersonas = models.IntegerField(default=0)
    DescuentoEspecial = models.BooleanField(default=False)
    DescuentoEn = models.IntegerField(default=0)
    DescuentoLibre = models.BooleanField(default=False)
    DescuentoCortesia = models.BooleanField(default=False)
    ValueNITClient = models.CharField(max_length=255,null=True)
    DirClient = models.CharField(verbose_name='Dirección',max_length=255,null=True)
    TotalSubsidio = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    QuitarSubsidio = models.BooleanField(default=False)
    EsPorCuentaPendiente = models.BooleanField(default=False)
    TipoOrden = models.IntegerField(default=0)
    IDOrdenCE = models.IntegerField(default=0)
    TipoEstadoCE = models.IntegerField(default=0)
    TotalMontoDelivery = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    EsNuevaCE = models.BooleanField(default=False)
    Notas = models.TextField(null=True)
    Payment_ID_CE = models.IntegerField(default=0)
    Delivery_Address_ID_CE = models.IntegerField(default=0)
    Driver_ID_CE = models.IntegerField(default=0)
    Driver_ID_EW = models.IntegerField(default=0)
    Want_FE_CE = models.BooleanField(default=False)
    Document_Type_ID_FE_CE = models.IntegerField(default=0)
    Document_ID_FE_CE = models.CharField(max_length=100, null=True)
    Email_Client_FE_CE = models.CharField(max_length=150, null=True)
    Email_Client_CE = models.CharField(max_length=150, null=True)
    Telefono_Client_CE = models.CharField(max_length=50, null=True)
    Nombre_Mesa_CE = models.CharField(max_length=150, null=True)
    Mesa_ID_CE = models.IntegerField(default=0)
    MetodoPago_CE = models.CharField(max_length=100, null=True)
    TipoConsumoCE = models.IntegerField(default=0)
    CobrarDeliveryCE = models.BooleanField(default=False)
    Eliminada_CE = models.BooleanField(default=False)
    Eliminada_Aplicada_CE = models.BooleanField(default=False)
    orden_impresa = models.BooleanField(default=False)
    CuponWeb = models.CharField(max_length=100, null=True)
    retencion = models.BooleanField(default=False)
    TypeCoupon = models.CharField(max_length=50, null=True)
    Coupons_Real_Value = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    Coupons_Perceived_Value = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    Client_IntegrationCode = models.CharField(max_length=100, null=True)
    TotalRedemptionsAvailablePerCoupon = models.IntegerField(default=0)
    TotalRedemptionsAvailablePerUser = models.IntegerField(default=0)
    #Campos personalizados
    cliente = models.TextField()
    empleado = models.CharField(max_length=200,null=False)
    detalles = models.TextField()
    sucursal = models.CharField(max_length=200,null=False)
    recibido = models.BooleanField(default=False)
    fecha_recibido = models.DateTimeField(null=True)
    creado = models.DateTimeField(auto_now_add=True)
