# Generated by Django 4.1.2 on 2022-11-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
