# Generated by Django 4.1.2 on 2022-11-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_alter_orden_id_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_recibido',
            field=models.DateTimeField(null=True),
        ),
    ]
